version: '3'
services: 
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    api:
        build: 
            dockerfile: Dockerfile.devback
            context: ./qrcode_secure_backend
        ports:
            - '22633:22633'
        volumes:
            - /app/node_modules
            - ./qrcode_secure_backend:/app
        environment: 
            - KEY=VALUE
    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./qrcode_secure_frontend_react
        volumes:
            - /app/node_modules
            - ./qrcode_secure_frontend_react:/app
